SELECT FECHA,
PERC
FROM (
	SELECT FECHA,
	CAST(ERROR/CONT AS FLOAT)*100 PERC
	FROM (
		SELECT TIME::TIMESTAMP::DATE AS FECHA,
		COUNT(*) AS CONT,
		CAST(SUM(CASE WHEN STATUS = '404 NOT FOUND' THEN 1 ELSE 0 END) AS FLOAT) AS ERROR
		FROM LOG
		GROUP BY 1
	)A
)B
WHERE PERC > 1;
