SELECT C.TITLE,
C.CONT
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY B.CONT DESC) AS RANKING,
	A.TITLE AS TITLE,
	B.CONT AS CONT
	FROM ARTICLES A,
	(
		SELECT SUBSTR(PATH, length('/article/') +1) AS CUSTOM_PATH, COUNT(*) AS CONT
		FROM LOG
		WHERE PATH LIKE '/article/%'
		AND STATUS = '200 OK'
		GROUP BY CUSTOM_PATH
	) B
	WHERE A.SLUG = B.CUSTOM_PATH
) C
WHERE C.RANKING <= 3;
